config/routes.rb
AppTest::Application.routes.draw do
  get "dynamic_pages/searchResult"
match 'searchResult' => 'dynamic_pages#searchResult'
  get "dynamic_pages/itemDetail"
match 'itemDetail' => 'dynamic_pages#itemDetail'
  get "dynamic_pages/myAccount"
match 'myAccount' => 'dynamic_pages#myAccount'
  get "dynamic_pages/recharge"
match 'recharge' => 'dynamic_pages#recharge'
  get "dynamic_pages/order"
match 'order' => 'dynamic_pages#order'

  get "dynamic_pages/cart"
match 'cart' => 'dynamic_pages#cart'

root :to => 'static_pages#home'

  get "static_pages/home"
match 'home' => 'static_pages#home'
get "static_pages/contact"
match 'contact' => 'static_pages#contact'
  get "static_pages/help"
  get "static_pages/about"
match 'about' => 'static_pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
  def searchResult
  end

  def itemDetail
  end

  def myAccount
  end

  def recharge
  end

  def order
  end

def cart
end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

def contact
end
end

app/helpers/application_helper.rb
module ApplicationHelper
def full_title(page_title)
	base_title = "Dbay"
if page_title.empty?
	base_title
else
	"#{base_title} | #{page_title}"
end
end
end

app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dynamic_pages/cart.html.erb
<h2 class = "orange">Items in your cart</h2>
<table class="table table table-bordered">
  <thead>
    <tr>
	  <th>#</th>
      <th><i class="icon-th-list"></i> Item overview</th>	  
      <th><i class=""></i> Actions</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>1</td>

	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
			  <p class="priceOld">$330.00</p>
			  <p class="priceNew">$320.00</p>	 
	  </div>
	  </td>
	  
	  <td>
	  <a href="#">remove</a>
	  </td>
	 </tr>
    <tr>
	  <td>2</td>

	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
			  <p class="priceOld">$330.00</p>
			  <p class="priceNew">$320.00</p>	
	  </div>
	  </td>
	  
	  <td>
	  <a href="#">remove</a>
	  </td>
	 </tr>
	 
  </tbody>
</table>
<a href = "order" class="btn btn-warning">Confirm order</a>
<button class="btn btn-primary">Back to shop</button>

app/views/dynamic_pages/itemDetail.html.erb
<div class = "row">
	<div class="span4">
	<img   src="http://placehold.it/320x240" alt="">
	</div>
	<div class="caption">
	  <h5 class ="orange">Item 1</h5>
	  <a href = "itemDetail"><p>Cras justo odio, dapibus ac facilisis in</p></a>
	  <p class="priceOld">$330.00</p>
	  <p class="priceNew">$320.00</p>
	  <hr>
	  <a href="cart" type="submit" class="btn  btn-warning btn-large">Buy now!</button></a>
	  
	</div>
</div>
<hr>
<h2 class ="orange small">Production details</h2>
<p>
Production detail goes here. Production detail goes here. Production detail goes here. Production detail goes here. Production detail goes here. 
</p>

app/views/dynamic_pages/myAccount.html.erb
<h2 class = "orange">Orders in process</h2>
<table class="table table table-bordered">
  <thead>
    <tr>
	  <th>#</th>
      <th><i class="icon-shopping-cart"></i> Order Placed:</th>	  
      <th><i class="icon-th-list"></i> Item overview</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>1</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>2</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>3</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
  </tbody>
</table>


<br>

<h2 class = "orange">Past orders</h2>
<table class="table table table-bordered">
  <thead>
    <tr>
	  <th>#</th>
      <th><i class="icon-shopping-cart"></i> Order Placed:</th>	  
      <th><i class="icon-th-list"></i> Item overview</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>1</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>2</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>3</td>
      <td><p>January 30, 2012</p>
	  <p>Order Number: 1112156-1544845</p>
	  </td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  </div>
	  </td>
	 </tr>
	 
  </tbody>
</table>

app/views/dynamic_pages/order.html.erb
<h2 class = "orange">Review Your Order</h2>
<table class="table table table-bordered">
  <thead>
    <tr>
	  <th>#</th>
      <th><i class="icon-th-list"></i> Item overview</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>1</td>
	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  	  <p class="priceOld">$330.00</p>
	  <p class="priceNew">$320.00</p>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>2</td>

	  <td>
	<img class="pull-left"  src="http://placehold.it/100x80" alt="">
	  <div class="caption"><a href="itemDetail">Item title and short description Link to responding item
	  </a>
	  	  <p class="priceOld">$330.00</p>
	  <p class="priceNew">$320.00</p>
	  </div>
	  </td>
	 </tr>
	 
	     <tr>
	  <td>Total</td>
	  <td>
	  $1,000.00
	  </td>
	 </tr>
	 
  </tbody>
</table>

<form class="form-horizontal">
        <fieldset>
          
		  <h2 class="orange">Billing Information:</h2>
          <div class="control-group">
            <label class="control-label" for="input01">First name</label>
            <div class="controls">
              <input type="text" class="input-xlarge" id="input01">
            </div>
          </div>
		  
          <div class="control-group">
            <label class="control-label" for="input02">Last name</label>
            <div class="controls">
              <input type="text" class="input-xlarge" id="input02">
            </div>
          </div>
		  
		   <div class="control-group">
            <label class="control-label" for="select01">Choose your card type</label>
            <div class="controls">
              <select id="select01">
                <option>Visa</option>
                <option>Master</option>
                <option>American Express</option>
                <option>JCB</option>
              </select>
            </div>
          </div>

		  <div class="control-group">
            <label class="control-label" for="input03">Card Number</label>
            <div class="controls">
              <input type="text" class="input-xlarge" id="input03">
            </div>
          </div>
		  
		  <div class="control-group">
            <label class="control-label" for="input04">Expire year</label>
            <div class="controls">
              <input type="text" class="input-small" id="input04">
            </div>
          </div>

		  	<div class="control-group">
			<label class="control-label" for="input05">Expire month</label>
            <div class="controls">
              <input type="text" class="input-small" id="input05">
            </div>
          </div>

		  	<div class="control-group">
			<label class="control-label" for="input06">3-digit security number</label>
            <div class="controls">
              <input type="text" class="input-small" id="input06">
            </div>
          </div>

		   <div class="control-group">
            <label class="control-label" for="select02">Locate your server</label>
            <div class="controls">
              <select id="select02">
                <option>Server A</option>
                <option>Server B</option>
                <option>Server C</option>
                <option>Server D</option>
              </select>
            </div>
          </div>
		  
		  <div class="control-group">
            <label class="control-label" for="input07">User Name</label>
            <div class="controls">
              <input type="text" class="input-xlarge" id="input07">
            </div>
          </div>

		  
          <div class="control-group">
            <label class="control-label" for="optionsCheckbox">Agreement</label>
            <div class="controls">
              <label class="checkbox">
                <input type="checkbox" id="optionsCheckbox" value="option1">
                Agreement
              </label>
            </div>
          </div>


          <div class="form-actions">
            <button type="submit" class="btn btn-warning">Place your order</button>
            <button class="btn">Cancel</button>
          </div>
        </fieldset>
      </form>

app/views/dynamic_pages/recharge.html.erb
<h1>DynamicPages#recharge</h1>
<p>Find me in app/views/dynamic_pages/recharge.html.erb</p>

app/views/dynamic_pages/searchResult.html.erb
	<div>
      <h3 class ="orange">search result for </h3>
		<div class = "row">
		  <div class="span2">
            <img   src="http://placehold.it/140x100" alt="">
			</div>
            <div class="caption">
              <h5 class ="orange">Item 1</h5>
              <a href = "itemDetail"><p>Click here to the item detail pages</p></a>
			  <p class="priceOld pull-left">$330.00</p>
			  <p class="priceNew">$320.00</p>
			</div>
			</div>
			<hr>
			<div class = "row">
		  <div class="span2">
            <img   src="http://placehold.it/140x100" alt="">
			</div>
            <div class="caption">
              <h5 class ="orange">Item 2</h5>
              <a href = "#"><p>Cras justo odio, dapibus ac facilisis in</p></a>
			 <p class="priceOld pull-left">$330.00</p>
			  <p class="priceNew">$320.00</p>
			</div>
			</div>
			<hr>
		<div class = "row">
		  <div class="span2">
            <img   src="http://placehold.it/140x100" alt="">
			</div>
            <div class="caption">
              <h5 class ="orange">Item 3</h5>
              <a href = "#"><p>Cras justo odio, dapibus ac facilisis in</p></a>
			<p class="priceOld pull-left">$330.00</p>
			  <p class="priceNew">$320.00</p>
			</div>
			</div>
						<hr>
<div class="pagination">
  <ul>
    <li><a href="#">Prev</a></li>
    <li class="active">
      <a href="#">1</a>
    </li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</div>

    </div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">DungeonBay.</a>
     All right reserved.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
		<li class ="brand", id="logo" ><%= link_to "DungeonBay", home_path %></li>
       
        <div class="nav-collapse">
          <ul class="nav pull-right">
		  <li><i class="icon-user icon-white nav-icon"></i></li>
            <li><%= link_to " My DungeonBay" , myAccount_path%> </li>
		<li><%= link_to " Recharge", recharge_path%></li>
            <li><%= link_to " Contact Us", contact_path %></li>
            <li><%= link_to " Cart", cart_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class = "container">

  <div class="container">
    <div class="row">
	<div class ="span2">      
	<div class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
          <li class="nav-header">Browse by Category</li>
          <li class="active"><a href="#">Equipments</a></li>
          <li><a href="#">Adventure Tools</a></li>
		  <li><a href="#">Category1</a></li>
		  <li><a href="#">Category2</a></li>
          <li class="nav-header">Browse by Roles</li>
          <li><a href="#">Category1</a></li>
          <li><a href="#">Category2</a></li>
          <li class="divider"></li>
          <li><a href="#">Help</a></li>
        </ul>
      </div>
      </div>
      <div class="span7">
	 <form class="form-search">
	 <div class = "form-actions">
	   <select class="medium">
                                <option>Select a category</option>
								<option>All</option>
                                <option>Category1</option>
                                <option>Category2</option>
                                <option>Category3</option>
                                <option>Category4</option>
      </select>
  <input type="text" class="input-large search-query">
  <a href="dynamic_pages/searchResult" type="submit" class="btn  btn-primary">Search in DungeonBay</a>
  </div>
</form>


	  <%= yield %>

	  </div>
      <div class="span3">
<ul class="thumbnails">
  <li class="span3">
    <a href="#" class="thumbnail">
      <img src="https://images-na.ssl-images-amazon.com/images/G/01/img12/office-products/300-column/panasonic_b2b-deals_300.png" alt="Advertisement goes here">
    </a>
  </li>
    <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://img-cdn.mediaplex.com/0/13001/101281/112911_AMZ_300x250_umberto_purple_AMZ_LP.jpg" alt="Advertisement goes here">
    </a>
	
  </li>
    <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://www.top1mmo.com/images/call-of-gods-pop-up-800-440.jpg" alt="Advertisement goes here">
    </a>
  </li>
    </li>
    <li class="span3">
    <a href="#" class="thumbnail">
      <img src="http://g-ecx.images-amazon.com/images/G/01/books/amyhorn/student_2_day_non-4_300x75._V142322511_.gif" alt="Advertisement goes here">
    </a>
  </li>

</ul>
      </div>
    </div>
	<%= render "layouts/footer" %>
  </div>
	

  </body>
</html>

app/views/layouts/b_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    '#' %></li>
              <li><%= link_to "Help",    '#' %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
<%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class ="row">
<blockquote class="pull-right">
  <p>DungeonBay is an one-stop shop for worthless virtual goods purchased with imaginary gold pieces.
 </p> 
 <small>Kenytt Avery</small>
</blockquote>
</div>

<div class ="row">
  <div class="span3">
  <h2>About</h2>
  <p>You can create an account in this shop and stock it with weapons, equipment, magic spells, and novelty items. </p>
  </div>
  <div class="span4">
  <h2>What can you do?</h2>
  <p>Players can buy, sell, trade, barter, or plead for someone to take an item off your hands. Who knows, maybe you can finally get rid of that +3 Sword of Yodeling.</p>
  </div>

</div>

app/views/static_pages/contact.html.erb
<h2>Contact Information</h2>
<br>

<table class="table">
  <thead>
    <tr>
	  <th>#</th>
      <th><i class="icon-user icon-blue"></i> Name</th>	  
      <th><i class="icon-envelope icon-blue"></i> Email Address</th>
    </tr>
  </thead>
  <tbody>
    <tr>
	  <td>1</td>
      <td>Michael Phillips</td>
	  <td>phillips@email.com</td>
	  </tr>
	  <tr>
	  <td>2</td>
      <td>Shaofen Chen</td>
	  <td>chen@email.com</td>
	  </tr>
	  <tr>
	  <td>3</td>
	  <td>Lisa Giss</td>
	  <td>giss@email.com</td>
	  </tr>
	  <tr>
	  <td>4</td>
	  <td>Mrunal Patel</td>
	  <td>patel@email.com</td>
	  </tr>
	  <tr>
	  <td>5</td>
	  <td>Junyi Feng</td>
	  <td>feng@email.com</td>
    </tr>
  </tbody>
</table>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div id="myCarousel" class="carousel slide">
            <div class="carousel-inner">
              <div class="item active">
                <img src="http://www.top1mmo.com/images/call-of-gods-pop-up-800-440.jpg" alt="">
                <div class="carousel-caption">
                  <h4>First Thumbnail label</h4>
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </div>
              </div>
              <div class="item">
                <img src="http://www.newgameseason.com/css/images/mass-effect.jpg" alt="">
                <div class="carousel-caption">
                  <h4>Second Thumbnail label</h4>
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </div>
              </div>
              <div class="item ">
                <img src="http://us.blizzard.com/_images/games/sc/wallpapers/wall2/wall2-1920x1200.jpg" alt="">
                <div class="carousel-caption">
                  <h4>Third Thumbnail label</h4>
                  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                </div>
              </div>
            </div>
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
          </div>
		  
		  <hr>
		  
	<div>
      <h3 class ="orange">Recommendations for You</h3>
    
      <ul class="thumbnails">
	  
      
          <li class="span2 ">
            <img src="http://placehold.it/160x120" alt="">
            <div class="caption">
              <h5 class ="orange">Item 1</h5>
              <a href = "#"><p>Cras justo odio, dapibus ac facilisis in</p></a>
              
            </div>
          </li>

       
        <li class="span2 recomment">
            <img src="http://placehold.it/160x120" alt="">
            <div class="caption">
              <h5 class ="orange">Item 2</h5>
              <a href = "#"><p>Cras justo odio, dapibus ac facilisis in</p></a>
              
            </div>
        </li>
		  <li class="span2 recomment">
      
            <img src="http://placehold.it/160x120" alt="">
            <div class="caption">
              <h5 class ="orange">Item 3</h5>
              <a href = "#"><p>Cras justo odio, dapibus ac facilisis in</p></a>
            
            </div>
        
        </li>
      </ul>
    </div>